version: '3.5'

services:
  db:
    image: mysql:5.7
    container_name: bd1-trabalho-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - '$HOME/.bd1-trabalho-mysql-data:/var/lib/mysql'
