version: '3.5'

services:
  db:
    image: ghcr.io/bd2020-1/database/vodan-mysql:latest
    container_name: vodan-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: project_vodan
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - ./mysql-data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: vodan-api
    ports:
      - 8000:8000
    environment:
      MYSQL_HOSTNAME: vodan-mysql
      MYSQL_DATABASE: project_vodan
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: abc123
    depends_on:
      - db